import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import * as XLSX from 'xlsx';
import { readExcelBytes } from '../parser.js';
import { runRules } from '../rules.js';

const [runtimePackages, sample, base = 'http://127.0.0.1:5173'] = process.argv.slice(2);
const require = createRequire(`${runtimePackages}/package.json`);
const { chromium } = require('playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const page = await context.newPage();
const errors = [], requests = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('request', request => requests.push(request.url()));
await mkdir('.tmp/browser', { recursive: true });
try {
  await page.goto(base); await page.locator('#login-form').waitFor();
  await page.locator('#password').fill('wrong'); await page.locator('#login-form button[type=submit]').click();
  assert.match(await page.locator('#login-error').innerText(), /chưa đúng/);
  await page.locator('#password').fill('TKB@2026'); await page.locator('#login-form button[type=submit]').click();
  await page.locator('#app').waitFor({ state: 'visible' });
  await page.screenshot({ path: '.tmp/browser/desktop-empty.png', fullPage: true });
  await page.locator('#file-input').setInputFiles(sample);
  await page.waitForFunction(() => !document.getElementById('check').disabled);
  await page.locator('#check').click();
  assert.equal(await page.locator('#stat-errors').innerText(), '1');
  assert.equal(await page.locator('#stat-warnings').innerText(), '1');
  await page.screenshot({ path: '.tmp/browser/desktop-results.png', fullPage: true });
  await page.locator('#day-filter').selectOption('THỨ BA');
  assert.equal(await page.locator('.issue').count(), 0);
  await page.locator('#day-filter').selectOption('');
  await page.locator('[data-view=schedule]').click();
  assert.equal(await page.locator('#schedule tbody tr').count(), 24);
  await page.locator('[data-day="THỨ TƯ"]').click();
  assert.equal(await page.locator('#schedule thead th').count(), 7);
  await page.locator('#teacher-search').fill('Trần Hồng Điệp');
  assert.equal(await page.locator('#schedule tbody tr').count(), 1);
  await page.locator('#teacher-search').fill('');
  await page.locator('[data-view=results]').click();
  await page.locator('#fix').click(); await page.waitForFunction(() => !document.getElementById('apply-all').disabled);
  await page.screenshot({ path: '.tmp/browser/desktop-preview.png', fullPage: true });
  // Preview has not altered the schedule.
  assert.equal(await page.locator('#stat-errors').innerText(), '1');
  await page.locator('[data-apply-issue="0"][data-option="0"]').click();
  assert.equal(await page.locator('#stat-errors').innerText(), '0');
  await page.locator('[data-view=history]').click(); await page.locator('#undo').click();
  assert.equal(await page.locator('#stat-errors').innerText(), '1');
  await page.locator('[data-view=results]').click();
  await page.locator('#fix').click(); await page.waitForFunction(() => !document.getElementById('apply-all').disabled);
  await page.locator('#apply-all').click();
  assert.equal(await page.locator('#stat-errors').innerText(), '0');
  assert.equal(await page.locator('#stat-warnings').innerText(), '1');
  assert.equal(await page.locator('#fix').isVisible(), false);
  const downloadEvent = page.waitForEvent('download'); await page.locator('#download').click();
  const download = await downloadEvent; await download.saveAs('.tmp/browser/exported.xlsx');
  const output = readExcelBytes(await readFile('.tmp/browser/exported.xlsx'), XLSX, 'exported.xlsx');
  assert.equal(runRules(output.data).length, 0); assert.equal(output.data.warnings.length, 1);
  assert.equal(output.workbook.Sheets['THỨ HAI'].C24.v, 'CC phân hiệu');
  await page.screenshot({ path: '.tmp/browser/desktop-fixed.png', fullPage: true });
  page.on('dialog', dialog => dialog.accept());
  // Invalid input must not destroy the current valid session.
  await page.locator('#file-input').setInputFiles({ name: 'broken.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from('not a workbook') });
  await page.waitForFunction(() => document.getElementById('notice').classList.contains('error'));
  assert.equal(await page.locator('#stat-lessons').innerText(), '454');
  const noData = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(noData, XLSX.utils.aoa_to_sheet([['a']]), 'Wrong');
  await page.locator('#file-input').setInputFiles({ name: 'missing.xlsx', mimeType: 'application/octet-stream', buffer: XLSX.write(noData, { type: 'buffer', bookType: 'xlsx' }) });
  await page.waitForFunction(() => document.getElementById('notice').textContent.includes('thiếu sheet'));
  await page.locator('#file-input').setInputFiles(sample); await page.waitForFunction(() => !document.getElementById('check').disabled);
  await page.locator('#check').click();
  for (const width of [390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `no horizontal page overflow at ${width}`);
    await page.screenshot({ path: `.tmp/browser/results-${width}.png`, fullPage: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#fix').click(); await page.waitForFunction(() => !document.getElementById('apply-all').disabled);
  await page.screenshot({ path: '.tmp/browser/mobile-preview.png', fullPage: true });
  await page.locator('#close-preview').click();
  await page.locator('[data-view=schedule]').click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: '.tmp/browser/mobile-schedule.png', fullPage: true });
  assert.equal(await page.evaluate(() => localStorage.length), 0);
  assert.ok(requests.every(url => url.startsWith(base)), 'No external network requests');
  await page.reload(); await page.locator('#app').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#stat-teachers').innerText(), '—');
  await page.locator('#logout').click(); await page.locator('#login').waitFor({ state: 'visible' });
  assert.equal(await page.evaluate(() => sessionStorage.getItem('tkb-access')), null);
  await page.screenshot({ path: '.tmp/browser/mobile-login.png', fullPage: true });
  assert.deepEqual(errors, []);
  const report = { passed: true, externalRequests: 0, consoleErrors: errors, downloadedFile: download.suggestedFilename(), viewports: [1440, 768, 390] };
  await writeFile('.tmp/browser/report.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
